workflows:

  my-workflow:

    name: My workflow name

    instance_type: linux_x2

    max_build_duration: 120
    
    environment:

      ubuntu: 20.04
        
    scripts:

      - lscpu && cat /etc/*-release && node -v && npm
