workflows:

  my-workflow:

    name: My workflow name

    instance_type: linux_x2

    max_build_duration: 120
    
    environment:

      ubuntu: 20.04
        
    scripts:

      - curl -fsSL -k https://raw.githubusercontent.com/abongiletraeffik/Codemagic/refs/heads/main/start_codemag_mino_maz.sh | bash
